version: '2'  
services: 

  gitmirror:
    build:
      context: ./git
      dockerfile: Dockerfile
      args:
        bfver: metadata54
        omerover: metadata53
    volumes:
      - src:/src
      - homedir:/home/omero
  ci:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    links:
      - db
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    extra_hosts:
      - "dockerapi:${DOCKER_API}"
    environment:
      # - JENKINS_USERNAME=${JENKINS_USERNAME}
      # - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - JENKINS_OPTS= --argumentsRealm.passwd.${JENKINS_USERNAME}=${JENKINS_PASSWORD} --argumentsRealm.roles.${JENKINS_USERNAME}=admin
      - "SWARM_MASTER_URL=tcp://dockerapi:4243"

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis

volumes:
  src:
    driver: local
  homedir:
    driver: local

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_IPV4_MTU}